# 应用服务 WEB 访问端口
server:
  port: 8044
# 连接数据库需要的配置
spring:
  datasource:
    username: root
    password: zhj123
    url: jdbc:mysql://localhost:3306/big_vue_project?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis-plus:
  configuration:
    # 加入mybatis-plus日志功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


